### ISSUE TITLE
deadd-notification-center not loading deadd.css

### ISSUE THREAD

**Issue by renanbrayner** [phuhl/linux_notification_center#173]
first of all thank you for sharing this beautyfull program with all of us, i love it ❤️
my issue is any css, even this:
```css
.blurredBG, #main_window, .blurredBG.low, .blurredBG.normal {
	border: 5px solid #FF0000;
}

.title {
    font-weight: bold;
    font-size: 32px;
    color: #FF0000;
}
```
is not being loaded, i'm currently using the dead.conf to set colors.

![image](https://user-images.githubusercontent.com/29386809/128044587-e5300369-c2bd-4720-aee3-d523ba78b9be.png)
![image](https://user-images.githubusercontent.com/29386809/128044661-2b3f3159-7f1c-4732-9435-b148b554d0a7.png)

i wish i knew haskell to help this project, but i'm a soywebdev 😞
