### ISSUE TITLE
Is it possible to exclude specific apps from the notification-center history?

### ISSUE THREAD

**Issue by Alexey104** [phuhl/linux_notification_center#204]
Hello!
In the example configuration file I can see that it is possible to use `match/modify` rules for specific apps in the `notification` section, which is great. If I don't want to see pop-up notifications from a specific app, I can use something like:
```
notification:
  modifications:
    match:
      app-name: "pa-applet"
    modify:
      timeout: 1
```
But is it possible to use similar rules in the `notification-center` section of the config? For example, when I change volume level, I want to see pop-up notifications from `pa-applet`, but I don't want to see such non-important events in history when using `kill -s USR1 $(pidof deadd-notification-center)`. Can I selectively exclude some `app-name`'s from the notification-center?

Regards.
