### ISSUE TITLE
Notification style selectors combining class name and urgency

### ISSUE THREAD

**Issue by joe-herbert** [phuhl/linux_notification_center#219]
Hi, I'm having an issue applying a background colour to my notifications. Here's a MWE.

I have the following added to the default `deadd.yml`:
```yml
- match:
    app-name: "notify-send"
  modify:
    class-name: "notify"
```
And my `deadd.css` file is just this:
```css
.notification.low {
    color: green;
}
.notification.normal {
    color: blue;
}
.notification.critical {
    color: red;
}

.notification.notify {
    background: yellow;
}

.notification.notify.normal {
    background: blue;
}
.notification.notify.critical {
    background: red;
}
.notification.notify.low {
    background: green;
}
```
And I've been testing this with:
```sh
notify-send -u low "low"
notify-send -u normal "normal"
notify-send -u critical "critical"
```
The result I'm getting is that the text colour is correctly set to green, blue and red respectively, but the background colour is always yellow. If I remove the block setting the background to yellow, the background is just white. It seems that when both urgency and class are in the selector, it doesn't match them.

Interestingly, if you replace all instances of `.notification` with `.notificationInCenter`, the notifications in the center are styled correctly, with both coloured foreground and background. This issue seems to only happen for notifications which pop up, not those in the center.

Any advice would be awesome, thanks.

**Comment by phuhl** [comment]
Hey,

after some experimentation I found that what you want should be possible with these classes:

```css
.normal.blurredBG.notification .notify {
    background: #blue;
}
.critical.blurredBG.notification .notify {
    background: red;
}
.low.blurredBG.notification .notify {
    background: green;
}
```
I do have to agree though, that the current class hierarchy is a bit fiddly. PR is welcome.

Does that solve your issue?
