### ISSUE TITLE
[bug] popup.default-timeout don't work

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [phuhl/linux_notification_center#225]
demo: https://0x0.st/s/yoDtsPQQEUs_2SBH8jNBJA/HQXR.mp4

linux_notification_center version: 2.0.3

**Comment by phuhl** [comment]
Cannot reproduce. Can you please share your config?

**Comment by phuhl** [comment]
From your config:

```yaml
notification:
  // ...
popup:
  // ...
  default-timeout: 10000
```

The popup section needs to be a subsection of the notification section. You'll need to indent it by two spaces. Hope that helps.
