### ISSUE TITLE
Fontsize of title

### ISSUE THREAD

**Issue by moukle** [phuhl/linux_notification_center#36]
How to change the fontsize of the title?

Notification seems to be uneffected by the following settings in my gtk.css
``` css
label.deadd-noti-center.notification.title {
	font-size: 1.5em;
}

/* Nor does label / .title work for me */
```

I am using latest AUR bin build `1.7.2-1`.
